
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.Database
{

using System;
    using System.Collections.Generic;
    
public partial class AwardPerson
{

    public int AwardPersonID { get; set; }

    public int AwardID { get; set; }

    public int PersonID { get; set; }

    public int YearAward { get; set; }

    public Nullable<System.DateTime> DateOfAward { get; set; }

    public string Comments { get; set; }



    public virtual Award Award { get; set; }

    public virtual Person Person { get; set; }

}

}
