
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.Database
{

using System;
    using System.Collections.Generic;
    
public partial class CommitteePerson
{

    public int CommitteeMemberID { get; set; }

    public int CommitteePositionID { get; set; }

    public int PersonID { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<bool> ActiveInd { get; set; }

    public string Comments { get; set; }

    public Nullable<bool> VolunteerInd { get; set; }



    public virtual CommitteePosition CommitteePosition { get; set; }

    public virtual Person Person { get; set; }

}

}
