
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Game
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Game()
    {

        this.GameTeams = new HashSet<GameTeam>();

    }


    public int GameID { get; set; }

    public int CourtID { get; set; }

    public Nullable<int> TournamentID { get; set; }

    public string MatchNo { get; set; }

    public string Venue { get; set; }

    public System.DateTime DatePlayed { get; set; }

    public Nullable<int> PrimaryUmpireID { get; set; }

    public Nullable<int> SecondaryUmpireID { get; set; }

    public Nullable<int> ReserveUmpireID { get; set; }

    public System.TimeSpan StartTime { get; set; }

    public System.TimeSpan FullTime { get; set; }

    public Nullable<int> ExtraTimeEnd { get; set; }

    public Nullable<int> MatchWonByTeamID { get; set; }

    public Nullable<int> Scorer1ID { get; set; }

    public Nullable<int> Scorer2ID { get; set; }

    public Nullable<int> TimeKeeper1ID { get; set; }

    public Nullable<int> TimeKeeper2ID { get; set; }

    public Nullable<int> DivisionID { get; set; }



    public virtual Court Court { get; set; }

    public virtual Division Division { get; set; }

    public virtual Person Person { get; set; }

    public virtual Person Person1 { get; set; }

    public virtual Person Person2 { get; set; }

    public virtual Person Person3 { get; set; }

    public virtual Person Person4 { get; set; }

    public virtual Team Team { get; set; }

    public virtual Person Person5 { get; set; }

    public virtual Person Person6 { get; set; }

    public virtual Tournament Tournament { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GameTeam> GameTeams { get; set; }

}

}
