
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.Database
{

using System;
    using System.Collections.Generic;
    
public partial class GameQuarter
{

    public int GameQuarterID { get; set; }

    public Nullable<int> GameTeamID { get; set; }

    public Nullable<int> QuarterTypeID { get; set; }

    public string CtrPass { get; set; }

    public string TeamGS { get; set; }

    public string TeamGA { get; set; }

    public Nullable<int> GoalShotAttempt { get; set; }

    public Nullable<int> GoalShotScored { get; set; }

    public Nullable<int> QuarterScore { get; set; }

    public Nullable<int> ProgressiveScore { get; set; }



    public virtual GameTeam GameTeam { get; set; }

    public virtual QuarterType QuarterType { get; set; }

}

}
