
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.Database
{

using System;
    using System.Collections.Generic;
    
public partial class GamePlayer
{

    public int GamePlayerID { get; set; }

    public int GameTeamID { get; set; }

    public int PlayerID { get; set; }

    public bool FirstQuarterInd { get; set; }

    public bool SecondQuarterInd { get; set; }

    public bool ThirdQuarterInd { get; set; }

    public bool FourthQuarterInd { get; set; }



    public virtual GameTeam GameTeam { get; set; }

    public virtual Person Person { get; set; }

}

}
