
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClassLibrary.Database
{

using System;
    using System.Collections.Generic;
    
public partial class Team
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Team()
    {

        this.Coaches = new HashSet<Coach>();

        this.Games = new HashSet<Game>();

        this.GameTeams = new HashSet<GameTeam>();

        this.TeamPlayers = new HashSet<TeamPlayer>();

        this.CoachAssistants = new HashSet<CoachAssistant>();

    }


    public int TeamID { get; set; }

    public string TeamName { get; set; }

    public Nullable<int> CoachID { get; set; }

    public Nullable<int> DivisionID { get; set; }

    public Nullable<int> CaptainID { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Coach> Coaches { get; set; }

    public virtual Division Division { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Game> Games { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<GameTeam> GameTeams { get; set; }

    public virtual Person Person { get; set; }

    public virtual Person Person1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TeamPlayer> TeamPlayers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CoachAssistant> CoachAssistants { get; set; }

}

}
